Output show.gif

Set TypingSpeed 0.2
Set FontSize 32
Set Width 2400
Set Height 1200

Hide
Type "go build ."
Enter
Type "clear"
Enter
Show

Type "./md"
Enter
Sleep 2

Type "i"
Sleep 0.5

# Content
Type "Hello world"
Enter
Enter
Type "md now is preview. thank you!"
Enter
Type "md is still in the very early state."

# do save file
Ctrl+S
Type "qwe.md"
Enter
Sleep 2
Ctrl+C

Hide
Type "clear"
Enter
Show

# view
Type "./md qwe.md"
Enter

Sleep 5s
