Output show.gif

Set TypingSpeed 0.2
Set FontSize 32
Set Width 2400
Set Height 1200

Type "./md"
Enter
Sleep 2

Type "i"
Sleep 0.5

# Content
Type "Hello world"
Enter 2
Type "Md is still in the very early state."
Enter 2
Type "So any suggestions for improving the program are welcome. thank you!"

# do save file
Ctrl+S
Type "qwe.md"
Enter
Sleep 2
Ctrl+C

Hide
Type "clear"
Enter
Show

# view
Type "./md qwe.md"
Enter

Sleep 3s
